In [12]:
import pandas as pd 

df_cavite = pd.read_csv("../data/cavite_33.csv",
   sep=";")

df_incendies= pd.read_csv(
    "../data/Incendies.csv",
    sep=";",
    encoding="utf-8",
    skiprows=3
) # 20-25


df_meteo = pd.read_csv("../data/MENSQ_33_previous-1950-2024.csv",
   sep=";")

df_carreaux = pd.read_csv("../data/carreaux_nivNaturel_met.csv",
   sep=",")

In [18]:
df_cavite.head()

,id,numCavite,indiceBSS,designationBSS,natureCavite,typeCavite,typeCaviteAppauvri,nomCavite,statut,confidentialite,...,cUserSaisie,cDateSaisie,cUserModif,dateValidationSaisie,dateValidationDiffusion,userValidationSaisie,userValidationDiffusion,statutValidation,dangerosite,Unnamed: 38
0,107549,AQIAA0020001,NaN,NaN,galeries filantes,carrière,carriere,Clottet_La_Boye,abandon,public,...,gironde@brgm.fr,2009-12-09,gironde@brgm.fr,2009-01-01,2011-08-22,S.BesdeBerc@brgm.fr,sbdbAdministrateur@brgm.fr,2,NaN,NaN
1,108175,AQIAA0020002,NaN,NaN,chambres et piliers,carrière,carriere,La_Boye,abandon,public,...,gironde@brgm.fr,2009-12-09,gironde@brgm.fr,2009-01-01,2011-08-22,S.BesdeBerc@brgm.fr,sbdbAdministrateur@brgm.fr,2,NaN,NaN
2,104150,AQIAA0020003,NaN,NaN,chambres et piliers,carrière,carriere,Talusson_Ouest_02,abandon,public,...,gironde@brgm.fr,2009-12-09,gironde@brgm.fr,2009-01-01,2011-08-22,S.BesdeBerc@brgm.fr,sbdbAdministrateur@brgm.fr,2,NaN,NaN
3,104629,AQIAA0020004,NaN,NaN,chambres et piliers,carrière,carriere,Talusson_Ouest_01,abandon,public,...,gironde@brgm.fr,2009-12-09,gironde@brgm.fr,2009-01-01,2011-08-22,S.BesdeBerc@brgm.fr,sbdbAdministrateur@brgm.fr,2,NaN,NaN
4,106978,AQIAA0020005,NaN,NaN,chambres et piliers,carrière,carriere,Chateau_de_Benauge_01,abandon,public,...,gironde@brgm.fr,2009-12-09,gironde@brgm.fr,2009-01-01,2011-08-22,S.BesdeBerc@brgm.fr,sbdbAdministrateur@brgm.fr,2,NaN,NaN

In [13]:
df_carreaux.head()

,idcar_nat,tmaille,ind,men,men_pauv,men_1ind,men_5ind,men_prop,men_fmp,ind_snv,...,ind_4_5,ind_6_10,ind_11_17,ind_18_24,ind_25_39,ind_40_54,ind_55_64,ind_65_79,ind_80p,ind_inc
0,CRS3035RES1000mN2032000E4250000,1000,636.0,338.1,101.1,179.0,15.0,108.0,30.0,12630411.8,...,12.1,32.6,36.5,26.1,113.9,130.9,91.9,111.0,52.0,0.0
1,CRS3035RES1000mN2032000E4251000,1000,394.5,153.0,30.9,43.2,17.0,46.1,20.2,7926187.1,...,10.0,43.1,41.2,17.2,68.8,80.9,45.7,39.9,29.2,0.0
2,CRS3035RES1000mN2033000E4250000,1000,201.5,89.1,15.0,30.9,6.1,58.9,11.4,5187800.7,...,4.7,8.8,15.0,10.1,24.1,52.8,32.2,30.9,15.1,0.9
3,CRS3035RES1000mN2033000E4251000,1000,152.0,67.8,5.3,21.0,1.0,48.9,6.2,4258506.8,...,0.0,2.9,9.8,12.1,30.6,30.4,38.2,21.1,2.9,0.0
4,CRS3035RES1000mN2034000E4252000,1000,146.0,63.3,16.8,16.8,3.1,38.8,8.1,3552678.5,...,5.0,11.0,12.0,8.0,24.8,29.2,22.1,23.8,8.1,0.0

In [15]:
print(df_carreaux.columns)
print(df_cavite.columns)
print(df_incendies.columns)
print(df_meteo.columns)

Index(['idcar_nat', 'tmaille', 'ind', 'men', 'men_pauv', 'men_1ind',
       'men_5ind', 'men_prop', 'men_fmp', 'ind_snv', 'men_surf', 'men_coll',
       'men_mais', 'log_av45', 'log_45_70', 'log_70_90', 'log_ap90', 'log_inc',
       'log_soc', 'ind_0_3', 'ind_4_5', 'ind_6_10', 'ind_11_17', 'ind_18_24',
       'ind_25_39', 'ind_40_54', 'ind_55_64', 'ind_65_79', 'ind_80p',
       'ind_inc'],
      dtype='object')
Index(['id', 'numCavite', 'indiceBSS', 'designationBSS', 'natureCavite',
       'typeCavite', 'typeCaviteAppauvri', 'nomCavite', 'statut',
       'confidentialite', 'raisonConfidentialite',
       'organismeChxConfidentialite', 'reperageGeographique', 'positionnement',
       'positionnementAppauvri', 'sourceCoordonnees', 'precisionXY',
       'dateValidite', 'auteurDescription', 'dateMajCavite', 'lambertOuvrage',
       'xOuvrage', 'yOuvrage', 'zOuvrage', 'xouvl2e', 'youvl2e', 'numInsee',
       'commentaires', 'caviteAssociee', 'cUserSaisie', 'cDateSaisie',
       'cUserModif', 'dateValidationSaisie', 'dateValidationDiffusion',
       'userValidationSaisie', 'userValidationDiffusion', 'statutValidation',
       'dangerosite', 'Unnamed: 38'],
      dtype='object')
Index(['Année', 'Numéro', 'Département', 'Code INSEE', 'Nom de la commune',
       'Date de première alerte', 'Surface parcourue (m2)',
       'Surface forêt (m2)', 'Surface maquis garrigues (m2)',
       'Autres surfaces naturelles hors forêt (m2)', 'Surfaces agricoles (m2)',
       'Autres surfaces (m2)', 'Surface autres terres boisées (m2)',
       'Surfaces non boisées naturelles (m2)',
       'Surfaces non boisées artificialisées (m2)',
       'Surfaces non boisées (m2)', 'Précision des surfaces',
       'Type de peuplement', 'Nature', 'Décès ou bâtiments touchés',
       'Nombre de décès', 'Nombre de bâtiments totalement détruits',
       'Nombre de bâtiments partiellement détruits', 'Précision de la donnée'],
      dtype='object')
Index(['NUM_POSTE', 'NOM_USUEL', 'LAT', 'LON', 'ALTI', 'AAAAMM', 'RR', 'QRR',
       'NBRR', 'RR_ME',
       ...
       'QNEIGETOTM', 'NEIGETOTAB', 'QNEIGETOTAB', 'NEIGETOTABDAT',
       'NBJNEIGETOT1', 'NBJNEIGETOT10', 'NBJNEIGETOT30', 'NBJGREL', 'NBJORAG',
       'NBJBROU'],
      dtype='object', length=162)

In [51]:
print(df.columns)

print(df["Département"].unique())

Index(['Année', 'Numéro', 'Département', 'Code INSEE', 'Nom de la commune',
       'Date de première alerte', 'Surface parcourue (m2)',
       'Surface forêt (m2)', 'Surface maquis garrigues (m2)',
       'Autres surfaces naturelles hors forêt (m2)', 'Surfaces agricoles (m2)',
       'Autres surfaces (m2)', 'Surface autres terres boisées (m2)',
       'Surfaces non boisées naturelles (m2)',
       'Surfaces non boisées artificialisées (m2)',
       'Surfaces non boisées (m2)', 'Précision des surfaces',
       'Type de peuplement', 'Nature', 'Décès ou bâtiments touchés',
       'Nombre de décès', 'Nombre de bâtiments totalement détruits',
       'Nombre de bâtiments partiellement détruits', 'Précision de la donnée'],
      dtype='object')
['56' '83' '2B' '06' '84' '13' '974' '34' '30' '05' '2A' '11' '04' '43'
 '39' '976' '07' '26' '47' '48' '40' '33' '09' '65' '64' '70' '29' '38'
 '73' '72' '52' '74' '24' '16' '19' '50' '55' '88' '66' '90' '76' '27'
 '82' '77' '67' '15' '81' '12' '35' '49' '71' '14' '68' '08' '22' '63'
 '02' '60' '89' '91' '41' '37' '46' '85' '59' '86' '44' '62' '54' '18'
 '17' '53' '31' '36' '23' '57' '45' '32' '21' '51' '58' '03' '87' '61'
 '69' '79' '42' '01' '10' '78' '25' '971' '972' '28' '80' '95']

In [59]:
df_13 = df[df["Département"].astype(str).str.strip() == "13"]
len(df_13)

1744

In [57]:
df_13 = df[df["Département"] == 13]
#len(df_13)
df["Département"].value_counts()

Département
13     1744
11     1129
2B      982
34      788
2A      782
       ...
78        4
62        3
51        2
971       1
95        1
Name: count, Length: 96, dtype: int64

In [61]:



df_temp= pd.read_csv(
    r"C:\Users\hamic\Desktop\MENSQ_13_previous-1950-2024.csv",
    sep=";",
    encoding="utf-8"
)
df_temp.head()

,NUM_POSTE,NOM_USUEL,LAT,LON,ALTI,AAAAMM,RR,QRR,NBRR,RR_ME,...,QNEIGETOTM,NEIGETOTAB,QNEIGETOTAB,NEIGETOTABDAT,NBJNEIGETOT1,NBJNEIGETOT10,NBJNEIGETOT30,NBJGREL,NBJORAG,NBJBROU
0,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196207,0.0,1.0,31.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196208,11.0,1.0,31.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196209,44.6,1.0,30.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196210,58.2,1.0,31.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196211,101.8,1.0,30.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
df_temps_2020_2024 = df_temp[
    pd.to_numeric(df_temp["AAAAMM"], errors="coerce").between(202001, 202412)
]
df_temps_2020_2024["AAAAMM"].unique()
print(df_temps_2020_2024.columns)

Index(['NUM_POSTE', 'NOM_USUEL', 'LAT', 'LON', 'ALTI', 'AAAAMM', 'RR', 'QRR',
       'NBRR', 'RR_ME',
       ...
       'QNEIGETOTM', 'NEIGETOTAB', 'QNEIGETOTAB', 'NEIGETOTABDAT',
       'NBJNEIGETOT1', 'NBJNEIGETOT10', 'NBJNEIGETOT30', 'NBJGREL', 'NBJORAG',
       'NBJBROU'],
      dtype='object', length=162)