In [1]:
import os
import pandas as pd

fichier = r"C:\Users\hamic\Desktop\consommation-annuelle-par-iris.csv"

print("Le fichier existe :", os.path.exists(fichier))

Le fichier existe : True

In [9]:
%pip install xlrd

Collecting xlrdNote: you may need to restart the kernel to use updated packages.

  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [ ]:
df = pd.read_csv(r"C:\Users\hamic\Desktop\BASE_TD_FILO_DEC_IRIS_2018.csv",
   sep=";")


df.describe()

,﻿id,description,url
count,11,11,11
unique,11,11,11
top,keolis_SIRI-Lite_general-message,Permet d'accéder aux messages d'alerte,https://bdx.mecatran.com/utw/ws/siri/2.0/borde...
freq,1,1,1

In [48]:
with open(
    r"C:\Users\hamic\Desktop\Incendies.csv",
    "r",
    encoding="utf-8"
) as f:
    
    for i in range(5):
        print(f.readline())

"Certaines données sont associées à l'ancienne version du formulaire incendie. Consultez la documentation pour plus d'informations."

"Nombre d'incendies suivant les critères de sélection : 16356"

"Critères de sélection =>";"Date de première alerte, de : 2020-01-01 00:00:00";"Date de première alerte, jusqu'à : 2025-12-31 23:59:00";"France entière";"Type de feu : F"

Année;Numéro;Département;"Code INSEE";"Nom de la commune";"Date de première alerte";"Surface parcourue (m2)";"Surface forêt (m2)";"Surface maquis garrigues (m2)";"Autres surfaces naturelles hors forêt (m2)";"Surfaces agricoles (m2)";"Autres surfaces (m2)";"Surface autres terres boisées (m2)";"Surfaces non boisées naturelles (m2)";"Surfaces non boisées artificialisées (m2)";"Surfaces non boisées (m2)";"Précision des surfaces";"Type de peuplement";Nature;"Décès ou bâtiments touchés";"Nombre de décès";"Nombre de bâtiments totalement détruits";"Nombre de bâtiments partiellement détruits";"Précision de la donnée"

2025;694;"56";"56179";"Pont-Scorff";"2025-01-01 01:08:00";1;1;;0;0;0;;;;;"Estimées";;"Involontaire (particulier)";"Non";;;;""

In [49]:
import pandas as pd

df= pd.read_csv(
    r"C:\Users\hamic\Desktop\Incendies.csv",
    sep=";",
    encoding="utf-8",
    skiprows=3
)

df.head(100)

,Année,Numéro,Département,Code INSEE,Nom de la commune,Date de première alerte,Surface parcourue (m2),Surface forêt (m2),Surface maquis garrigues (m2),Autres surfaces naturelles hors forêt (m2),...,Surfaces non boisées artificialisées (m2),Surfaces non boisées (m2),Précision des surfaces,Type de peuplement,Nature,Décès ou bâtiments touchés,Nombre de décès,Nombre de bâtiments totalement détruits,Nombre de bâtiments partiellement détruits,Précision de la donnée
0,2025,694,56,56179,Pont-Scorff,2025-01-01 01:08:00,1,1.0,NaN,0.0,...,NaN,NaN,Estimées,NaN,Involontaire (particulier),Non,NaN,NaN,NaN,NaN
1,2025,8949,83,83126,La Seyne-sur-Mer,2025-01-01 01:46:00,200,0.0,200.0,0.0,...,NaN,NaN,Estimées,1.0,NaN,Non,NaN,NaN,NaN,NaN
2,2025,26,2B,2B007,Albertacce,2025-01-01 13:04:00,10000,0.0,10000.0,0.0,...,NaN,NaN,Estimées,NaN,NaN,Non,NaN,NaN,NaN,NaN
3,2025,1,06,06148,Tourrettes-sur-Loup,2025-01-02 09:22:00,20,0.0,20.0,0.0,...,NaN,NaN,Estimées,NaN,NaN,Non,NaN,NaN,NaN,NaN
4,2025,27,2B,2B049,Calenzana,2025-01-02 10:35:00,2000,0.0,2000.0,0.0,...,NaN,NaN,Estimées,NaN,NaN,Non,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025,315,34,34341,Villeveyrac,2025-02-26 14:12:00,4442,4442.0,0.0,0.0,...,NaN,NaN,Mesurées,NaN,Involontaire (travaux),Non,NaN,NaN,NaN,NaN
96,2025,13991,84,84032,Caseneuve,2025-02-26 16:19:23,500,500.0,NaN,NaN,...,NaN,NaN,Estimées,NaN,NaN,Non,NaN,NaN,NaN,NaN
97,2025,7589,11,11069,Carcassonne,2025-02-26 18:26:00,1,0.0,1.0,0.0,...,NaN,NaN,Mesurées,NaN,Involontaire (particulier),Non,NaN,NaN,NaN,NaN
98,2025,344,06,06074,Lantosque,2025-02-27 11:59:00,200,0.0,200.0,0.0,...,NaN,NaN,Estimées,NaN,Involontaire (particulier),Non,NaN,NaN,NaN,NaN
99,2025,1529,13,13010,Barbentane,2025-02-28 15:47:00,1000,1000.0,0.0,0.0,...,NaN,NaN,Estimées,NaN,Malveillance,Non,NaN,NaN,NaN,NaN

In [51]:
print(df.columns)

print(df["Département"].unique())

Index(['Année', 'Numéro', 'Département', 'Code INSEE', 'Nom de la commune',
       'Date de première alerte', 'Surface parcourue (m2)',
       'Surface forêt (m2)', 'Surface maquis garrigues (m2)',
       'Autres surfaces naturelles hors forêt (m2)', 'Surfaces agricoles (m2)',
       'Autres surfaces (m2)', 'Surface autres terres boisées (m2)',
       'Surfaces non boisées naturelles (m2)',
       'Surfaces non boisées artificialisées (m2)',
       'Surfaces non boisées (m2)', 'Précision des surfaces',
       'Type de peuplement', 'Nature', 'Décès ou bâtiments touchés',
       'Nombre de décès', 'Nombre de bâtiments totalement détruits',
       'Nombre de bâtiments partiellement détruits', 'Précision de la donnée'],
      dtype='object')
['56' '83' '2B' '06' '84' '13' '974' '34' '30' '05' '2A' '11' '04' '43'
 '39' '976' '07' '26' '47' '48' '40' '33' '09' '65' '64' '70' '29' '38'
 '73' '72' '52' '74' '24' '16' '19' '50' '55' '88' '66' '90' '76' '27'
 '82' '77' '67' '15' '81' '12' '35' '49' '71' '14' '68' '08' '22' '63'
 '02' '60' '89' '91' '41' '37' '46' '85' '59' '86' '44' '62' '54' '18'
 '17' '53' '31' '36' '23' '57' '45' '32' '21' '51' '58' '03' '87' '61'
 '69' '79' '42' '01' '10' '78' '25' '971' '972' '28' '80' '95']

In [59]:
df_13 = df[df["Département"].astype(str).str.strip() == "13"]
len(df_13)

1744

In [57]:
df_13 = df[df["Département"] == 13]
#len(df_13)
df["Département"].value_counts()

Département
13     1744
11     1129
2B      982
34      788
2A      782
       ...
78        4
62        3
51        2
971       1
95        1
Name: count, Length: 96, dtype: int64

In [61]:



df_temp= pd.read_csv(
    r"C:\Users\hamic\Desktop\MENSQ_13_previous-1950-2024.csv",
    sep=";",
    encoding="utf-8"
)
df_temp.head()

,NUM_POSTE,NOM_USUEL,LAT,LON,ALTI,AAAAMM,RR,QRR,NBRR,RR_ME,...,QNEIGETOTM,NEIGETOTAB,QNEIGETOTAB,NEIGETOTABDAT,NBJNEIGETOT1,NBJNEIGETOT10,NBJNEIGETOT30,NBJGREL,NBJORAG,NBJBROU
0,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196207,0.0,1.0,31.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196208,11.0,1.0,31.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196209,44.6,1.0,30.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196210,58.2,1.0,31.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13001002,AIX-PUYRICARD,43.593333,5.413333,314,196211,101.8,1.0,30.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
df_temps_2020_2024 = df_temp[
    pd.to_numeric(df_temp["AAAAMM"], errors="coerce").between(202001, 202412)
]
df_temps_2020_2024["AAAAMM"].unique()
print(df_temps_2020_2024.columns)

Index(['NUM_POSTE', 'NOM_USUEL', 'LAT', 'LON', 'ALTI', 'AAAAMM', 'RR', 'QRR',
       'NBRR', 'RR_ME',
       ...
       'QNEIGETOTM', 'NEIGETOTAB', 'QNEIGETOTAB', 'NEIGETOTABDAT',
       'NBJNEIGETOT1', 'NBJNEIGETOT10', 'NBJNEIGETOT30', 'NBJGREL', 'NBJORAG',
       'NBJBROU'],
      dtype='object', length=162)